### ISSUE TITLE
Support HEIF file format

### ISSUE THREAD

**Issue by jhspetersson** [kamadak/exif-rs#9]
HEIF is the default one for photos taken with iOS since version 11.

Targeting https://github.com/jhspetersson/fselect/issues/65

**Comment by kamadak** [comment]
This library is for parsing Exif attributes. Retrieving an Exif data block from a container is basically out of scope.  JPEG (as a container) is supported only because the Exif standard specifies it.

That said, I understand that it would be convenient if major containers were supported out of the box (and without heavy dependencies), so I will think about it and probably add support for HEIF soon.

In the meantime, please extract the Exif data block by yourself with some HEIF library.  For example, see this: <https://github.com/Cykooz/libheif-rs/blob/e44212097dbd25c122edf8621b98e7f9c9003b48/tests/read_test.rs#L95-L102>.

**Comment by kamadak** [comment]
Version 0.5 includes HEIF support.  Also, AVIF is automatically supported because it reuses the HEIF container.

**Comment by jhspetersson** [comment]
Awesome! Thank you so much for the implementing that!
